### ISSUE TITLE
Ajouter un README ou une vignette

### ISSUE THREAD

**Issue by liatia** [CharlesJB/anno#3]

**Comment by CharlesJB** [comment]
# TODO:

- [ ] Ajouter une section "Introduction" qui décrit le but du paquet
- [ ] Ajouter une section "Usage" qui décrit l'usage de base de la fonction du paquet (sans avoir à entrer dans les détails de tous les paramètres, juste à mentionner qu'on peut appeler le man page avec ?nom_de_la_fonction).
- [ ] Ajouter une section "Outputs" qui décrit tous les fichiers de sorties qui sont créés et s'il faut mettre des options pour qu'ils soient produits.

**Comment by EmeTexe** [comment]
Done in 4ab9bd7e935aec255f7d74c381b24ceeb2b36955. Closing issue

**Comment by CharlesJB** [comment]
Serait-il possible d'ajouter cette information dans le README.md également?
