### ISSUE TITLE
Appeler une seule fois extract_anno

### ISSUE THREAD

**Issue by CharlesJB** [CharlesJB/anno#8]
La fonction `extract_anno` est appelée trois fois:

* https://github.com/CharlesJB/anno/blob/master/R/prepare_anno.R#L119
* https://github.com/CharlesJB/anno/blob/master/R/prepare_anno.R#L123
* https://github.com/CharlesJB/anno/blob/master/R/prepare_anno.R#L159

Déjà, à la ligne [119](https://github.com/CharlesJB/anno/blob/master/R/prepare_anno.R#L119) et [123](https://github.com/CharlesJB/anno/blob/master/R/prepare_anno.R#L123), la fonction `extract_anno` est appelée sur exactement les mêmes données. On ne devrait pas appeler cette fonction sur les données nettoyées car la seule différence avec les données brutes est au niveau des nom (le identifiants ensembl devraient être identiques).

De plus, étant donnée que l'opération de `mapIds` est relativement longue, on devrait éviter de la répéter plusieurs fois. On devrait plutôt faire comme aux lignes [174 à 176](https://github.com/CharlesJB/anno/blob/master/R/prepare_anno.R#L174-L176) où on fait un sous-ensemble des données originales.

## TODO:

- [x] Remplacer les fonction `extract_anno` qui ne sont pas sur les données brutes soit par un filtre (i.e.: la fonction `dplyr::filter`) ou bien en utilisant un indice comme pour les lignes [174 à 176](https://github.com/CharlesJB/anno/blob/master/R/prepare_anno.R#L174-L176).
- [x] Ajouter une validation dans la fonction [`save_anno_resuts`](https://github.com/CharlesJB/anno/blob/master/R/prepare_anno.R#L345-L357) pour s'assurer que les identifiants sont identiques pour le fasta et pour l'annotation (on doit retrouver exactement les mêmes identifiants, exactement dans le même ordre).
- [x] Incrémenter la version du paquet dans le fichier `DESCRIPTION`.
